networks:
  sistema-estoque-cd:
    name: sistema-estoque-cd

services:
  app-cd:
    container_name: app-cd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres-cd
    networks:
      - sistema-estoque-cd
    # ports: #dev
    # - "8000:8000"
    # - "5173:5173"
    entrypoint: /usr/local/bin/entrypoint.sh

  postgres-cd:
    container_name: db-cd
    image: postgres:15
    restart: always
    volumes:
      - ./docker/postgres/data-cd:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - sistema-estoque-cd

  web-cd:
    container_name: web-server-cd
    image: nginx:stable-alpine
    restart: always
    ports:
      - "170:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sistema-estoque-cd