networks:
  sistema-estoque:
    name: sistema-estoque

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - sistema-estoque
    ports: #dev
    - "8000:8000"
    - "5173:5173"

  postgres:
    container_name: db
    image: postgres:15
    restart: always
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - sistema-estoque

  web:
    container_name: web-server
    image: nginx:stable-alpine
    restart: always
    ports:
      - "85:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sistema-estoque