<?php

use App\Domain\Enums\AccountType;
use App\Domain\Enums\MovementCategory;
use App\Domain\Enums\MovementDirection;
use App\Domain\Financial\ManualMovement;

describe('ManualMovement', function () {

    it('builds an income as a credit into the principal account', function () {
        $movement = ManualMovement::make(MovementCategory::Income, amount: 3257.03);

        expect($movement->account)->toBe(AccountType::Principal)
            ->and($movement->direction)->toBe(MovementDirection::Credit)
            ->and($movement->category)->toBe(MovementCategory::Income)
            ->and($movement->amount)->toBe(3257.03)
            ->and($movement->quantity)->toBeNull()
            ->and($movement->unitPrice)->toBeNull();
    });

    it('builds an expense as a debit from the principal account', function () {
        $movement = ManualMovement::make(MovementCategory::Expense, amount: 207.05);

        expect($movement->account)->toBe(AccountType::Principal)
            ->and($movement->direction)->toBe(MovementDirection::Debit)
            ->and($movement->amount)->toBe(207.05);
    });

    it('builds a tf2 purchase with amount derived from quantity times unit price', function () {
        $movement = ManualMovement::make(MovementCategory::Tf2Purchase, quantity: 130, unitPrice: 15.10);

        expect($movement->account)->toBe(AccountType::Principal)
            ->and($movement->direction)->toBe(MovementDirection::Debit)
            ->and($movement->amount)->toBe(1963.00)
            ->and($movement->quantity)->toBe(130.0)
            ->and($movement->unitPrice)->toBe(15.10);
    });

    it('rounds the tf2 purchase amount half-up to the cent', function () {
        $movement = ManualMovement::make(MovementCategory::Tf2Purchase, quantity: 2.5, unitPrice: 10.13);

        // 2.5 × 10.13 = 25.325 → 25.33
        expect($movement->amount)->toBe(25.33);
    });

    it('builds a fund withdrawal as a debit from the chosen fund', function () {
        $fromReinvestment = ManualMovement::make(
            MovementCategory::FundWithdrawal,
            amount: 100.00,
            fund: AccountType::Reinvestment,
        );
        $fromEmergency = ManualMovement::make(
            MovementCategory::FundWithdrawal,
            amount: 50.00,
            fund: AccountType::Emergency,
        );

        expect($fromReinvestment->account)->toBe(AccountType::Reinvestment)
            ->and($fromReinvestment->direction)->toBe(MovementDirection::Debit)
            ->and($fromEmergency->account)->toBe(AccountType::Emergency);
    });

    it('rejects a fund withdrawal targeting the principal account', function () {
        expect(fn () => ManualMovement::make(
            MovementCategory::FundWithdrawal,
            amount: 100.00,
            fund: AccountType::Principal,
        ))->toThrow(InvalidArgumentException::class);
    });

    it('rejects a fund withdrawal without a target fund', function () {
        expect(fn () => ManualMovement::make(MovementCategory::FundWithdrawal, amount: 100.00))
            ->toThrow(InvalidArgumentException::class);
    });

    it('rejects a non-positive amount', function () {
        expect(fn () => ManualMovement::make(MovementCategory::Income, amount: 0))
            ->toThrow(InvalidArgumentException::class);
        expect(fn () => ManualMovement::make(MovementCategory::Expense, amount: -5))
            ->toThrow(InvalidArgumentException::class);
    });

    it('rejects a tf2 purchase with non-positive quantity or price', function () {
        expect(fn () => ManualMovement::make(MovementCategory::Tf2Purchase, quantity: 0, unitPrice: 15.10))
            ->toThrow(InvalidArgumentException::class);
        expect(fn () => ManualMovement::make(MovementCategory::Tf2Purchase, quantity: 130, unitPrice: 0))
            ->toThrow(InvalidArgumentException::class);
    });

    it('rejects categories generated by the closing cascade', function () {
        expect(fn () => ManualMovement::make(MovementCategory::PartnerDistribution, amount: 100))
            ->toThrow(InvalidArgumentException::class);
        expect(fn () => ManualMovement::make(MovementCategory::ReinvestmentTransfer, amount: 100))
            ->toThrow(InvalidArgumentException::class);
    });

    it('rejects the opening category, which is bootstrap-only', function () {
        expect(fn () => ManualMovement::make(MovementCategory::Opening, amount: 100))
            ->toThrow(InvalidArgumentException::class);
    });
});
